VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IResourceCreator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'@Folder("API.Utils.ResourceManager")
'@Exposed
Option Explicit

Public Function tryCreate(Optional ByVal resourceIdentifier As Variant, Optional ByVal resourceArgs As Variant, Optional ByRef outResource As Variant) As Boolean
    tryCreate = False
End Function
